healthy
healthy neat

diff --git a/cmd/node/Dockerfile b/cmd/node/Dockerfile
--- a/cmd/node/Dockerfile
+++ b/cmd/node/Dockerfile
@@ -15,7 +15,7 @@ COPY . .
 RUN npm install --production
 RUN npm cache clean --force
 
-#ENV checkhealth="wget -T 3 -qS --spider 127.0.0.1:${app_port}${app_path}/healthcheck"
-#HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=120s CMD $checkhealth || exit 1
+#ENV healthy="wget -T 3 -qS --spider 127.0.0.1:${app_port}${app_path}/healthcheck"
+#HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=120s CMD $healthy || exit 1
 
 CMD [ "node", "server.js" ]
