change app_prefix to app_path
1. change app_prefix to app_path
2. upgrade healthcheck

diff --git a/cmd/node/Dockerfile b/cmd/node/Dockerfile
--- a/cmd/node/Dockerfile
+++ b/cmd/node/Dockerfile
@@ -3,10 +3,10 @@ ENV NODE_ENV=production
 #-- define this to get args from docker build-arg
 ARG ci_env
 ARG ci_app_port
-ARG ci_app_prefix
+ARG ci_app_path
 #-----
 ENV app_env=${ci_env:-"dev"}
-ENV app_prefix=${ci_app_prefix:-"/api-debug-node"}
+ENV app_path=${ci_app_path:-"/api-debug-node"}
 ENV app_port=${ci_app_port:-"80"}
 
 WORKDIR /app
@@ -14,5 +14,8 @@ COPY . .
 
 RUN npm install --production
 RUN npm cache clean --force
+
+#ENV checkhealth="wget -T 3 -qS --spider 127.0.0.1:${app_port}${app_path}/healthcheck"
+#HEALTHCHECK --interval=30s --timeout=5s --retries=3 --start-period=120s CMD $checkhealth || exit 1
 
 CMD [ "node", "server.js" ]
